FROM mhart/alpine-node:base-4.8.0

RUN addgroup -g 10001 app && \
    adduser -D -G app -h /app -u 10001 app
WORKDIR /app

# S3 bucket in Cloud Services prod IAM
ADD https://s3.amazonaws.com/dumb-init-dist/v1.2.0/dumb-init_1.2.0_amd64 /usr/local/bin/dumb-init
RUN chmod +x /usr/local/bin/dumb-init
ENTRYPOINT ["/usr/local/bin/dumb-init", "--"]

RUN apk add --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing/ --no-cache yarn
RUN apk add --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ --no-cache graphicsmagick

USER app

COPY yarn.lock yarn.lock
COPY package.json package.json
COPY scripts/check_gm.sh scripts/check_gm.sh

RUN yarn install --production --pure-lockfile && rm -rf ~app/.cache/yarn /tmp/*

COPY . /app
